### PR TITLE
Create helm chart

### PR DESCRIPTION
**Pull request by hanzala1234**

### CODE REVIEW

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-search:SNAPSHOT-PR-9-36550f54` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-search:SNAPSHOT-PR-9-e95e697d` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-search:SNAPSHOT-PR-9-72bc5770` is available

**Review by kahootali — APPROVED** [review]

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-search:SNAPSHOT-PR-9-88f37c69` is available

**Pull request merged**
